# -*- coding: utf-8 -*-
"""03. 반복구조

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hN1yS4IaTlTiHe7zmEwhzOhuaT8midxM
"""

#예제18 while 반복문 사용해서 1부터 10까지 출력

i = 1

while i <= 10:
    print(i, end = " ")
    i = i+1

#예제19 for반복문을 사용해서 1부터 10까지 출력

for i in range(1,11):
    print(i, end = " ")

#예제20 반복문을 사용해 숫자 10부터 1까지 출력

for i in range(10, 0, -1):
    print(i, end = " ")

#예제21 숫자 1부터 100까지의 합 구하기

sum = 0
for i in range(1, 101):
    sum += i

print(sum)

#예제22 1부터 100까지의 수 중 짝수의 합 구하기(1)

sum = 0
for i in range(0, 101, 2):
    sum += i

print(sum)

#예제23  1부터 100까지의 수 중 짝수의 합 구하기(2)

sum = 0
for i in range(1, 101):
    if i % 2 != 0: continue
    sum += i

print(sum)

#예제24 1, -2, 3, -4 ... 99, -100 의 합 구하기

sum = 0
for i in range(1, 101):
    if i % 2 == 0: sum -= i
    else: sum += i

print(sum)

#예제25 계승 구하기

fact = 1
for i in range(5, 0, -1):
    fact *= i

print(fact)

#예제26 약수 구하기

num = int(input("정수를입력하세요 : "))

for i in range(1, num+1):
    if num % i == 0:
        print(i, end = " ")

#예제27 공약수 구하기

num1 = int(input("첫 번째 정수를입력하세요 : "))
num2 = int(input("두 번째 정수를입력하세요 : "))

if num1 - num2 < 0:
    for i in range(1, num1+1):
        if num1 % i == 0 and num2 % i == 0:
            print(i, end = " ")
else:
    for i in range(1, num2+1):
        if num2 % i == 0 and num1 % i == 0:
            print(i, end = " ")

#예제28 최대공약수 구하기

num1 = int(input("첫 번째 정수를입력하세요 : "))
num2 = int(input("두 번째 정수를입력하세요 : "))
bignum = 0

if num1 - num2 < 0:
    for i in range(1, num1+1):
        if num1 % i == 0 and num2 % i == 0: bignum = i
else:
    for i in range(1, num2+1):
        if num2 % i == 0 and num1 % i == 0: bignum = i

print(bignum)

#예제29 소수 판별하기

num = int(input("정수를 입력하세요 : "))
numlist = []

for i in range(1, num+1):
    if num % i == 0: numlist.append(i)

if len(numlist) == 2: print("소수입니다.")
else: print("소수가 아닙니다.")

# 예제30 피보나치 수열 구하기

snum = int(input("수열 개수 입력 : "))
num1 = 1
num2 = 1
num3 = 0

print(f"{num1} {num2}", end = " ")

for i in range(1, snum+1):
    num3 = num1 + num2
    print(num3, end = " ")
    num1 = num2
    num2 = num3

# 예제31 최댓값 구하기


numlist = []

while True:
    num = int(input("정수를 입력하세요('0'입력시 최댓값 계산) : "))
    numlist.append(num)
    if num == 0: break

numlist.sort()
print(f"최대값 : {numlist.pop()}")

#예제32 직각삼각형 모양 수 출력

for i in range(1, 6):
    for j in range(1, i+1):
        print(j, end = " ")
    print("\n")

#예제33 1부터 10까지의 정수에 대한 약수 구하기

for i in range(1, 11):
    print(f"{i}의 약수 : ", end = "")
    for j in range(1, i+1):
        if i % j != 0: continue
        print(j, end=" ")
    print("\n")

#예제34 2부터 100까지의 소수 구하기

for i in range(2, 101):
    numlist = []

    for j in range(1, i+1):
        if i % j == 0: numlist.append(j)

    if len(numlist) == 2:
        print(i, end = " ")

#예제35 1+(1+2)+ ... +(1+2+...+9+10) 구하기

sum = 0

for i in range(1, 11):
    num = 0
    for j in range(1, i+1):
        num += j
    sum += num

print(sum)

#예제36 구구단

for i in range(2, 10):
    for j in range(1, 10):
        print(f"{i} x {j} = {i*j}",end ="\t")
    print("\n")

    